name: Deploy Carbon Frontend to GitHub Pages

on:
  workflow_dispatch:
  
  push:
    paths:
      - 'carbon-jsts-code/**'
      - '.github/workflows/node.js.yml'
      - '.github/workflows/deploy-frontend-gh-pages.yml'
      - 'carbon-jdk-code/libs/carbonlog-model/**'
    branches: [ "main" ]

  workflow_run:
    workflows: ["Node.js CI"]
    branches: [ "main" ]
    types:
      - completed

defaults:
  run:
    working-directory: ./carbon-jsts-code/carbonlogger-frontend

jobs:

  build-model:
    uses: ./.github/workflows/gradle-build-model.yml

  build:
    runs-on: ubuntu-latest
    needs: ['build-model']

    steps:
      - uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24.13'

      - name: setup pnpm
        uses: 'pnpm/action-setup@v4'
        with:
          version: '10.28.2'

      - name: Download model artifact
        uses: actions/download-artifact@v7
        with:
          name: carbonlog-model-build
          path: carbon-jdk-code/libs/carbonlog-model/build/

      - name: Install Dependencies
        working-directory: ./carbon-jsts-code
        run: pnpm install

      - name: Rewrite Service Worker Path in Index
        run: sed -i 's@/sw.js@${{ github.event.repository.name }}/sw.js@g' ./index.html && cat ./index.html

      - name: Replace Paths in Manifest
        run: sed -i 's@"/"@"/${{ github.event.repository.name }}/"@g' ./public/manifest.json && cat ./public/manifest.json

      - name: Vite Build
        run: pnpm run build --base=/${{ github.event.repository.name }}/

      - name: Rewrite Manifest Path in built Index
        working-directory: ./carbon-jsts-code/carbonlogger-frontend/dist
        run: sed -i 's@manifest.json@${{ github.event.repository.name }}/manifest.json@g' ./index.html && cat index.html

      - name: Redirect 404 to Index for SPA
        run: cp dist/index.html dist/404.html

      - name: kurwa debug index.html
        run: cat dist/index.html

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: carbon-jsts-code/carbonlogger-frontend/dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
