name: Node.js CI

on:
  push:
    paths:
      - 'carbon-jsts-code/**'
      - 'carbon-jdk-code/libs/carbonlog-model/**'
      - '.github/workflows/node.js.yml'
    branches: [ "main" ]
  pull_request:
    paths:
      - 'carbon-jsts-code/**'
      - 'carbon-jdk-code/libs/carbonlog-model/**'
      - '.github/workflows/node.js.yml'
    branches: [ "main" ]

jobs:

  build-model:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5.0.0
    - name: gradle build
      working-directory: ./carbon-jdk-code
      run: ./gradlew libs:carbonlog-model:build
    - name: Upload model artifact
      uses: actions/upload-artifact@v4
      with:
        name: carbonlog-model-build
        path: carbon-jdk-code/libs/carbonlog-model/build/

  build:
    runs-on: ubuntu-latest
    needs: ['build-model']
    steps:
    - name: Check out code
      uses: actions/checkout@v6
    - name: Download model artifact
      uses: actions/download-artifact@v4
      with:
        name: carbonlog-model-build
        path: carbon-jdk-code/libs/carbonlog-model/build/
    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    - name: setup pnpm
      uses: 'pnpm/action-setup@v4'
      with:
        version: '10.28.1'
    - name: install dependencies
      working-directory: ./carbon-jsts-code
      run: |
        pnpm i
    - name: pnpm build
      working-directory: ./carbon-jsts-code
      run: |
        pnpm run --if-present -r build
    - name: pnpm test
      working-directory: ./carbon-jsts-code
      run: |
        pnpm run --if-present -r test:ci